### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LewisCraik**
Changed get example request to athlete/stats to clarify point raised in #44.

### CODE REVIEW

**Comment by mjaschen** [comment]
I'd suggest to use an endpoint which supports additional query parameters to show how use them. 

A good example would be [List Athlete Activities](https://developers.strava.com/docs/reference/#api-Activities-getLoggedInAthleteActivities).

```php
$api->get(
    'athlete/activities', 
    [
        'per_page' => 10, 
        'page' => 3,
    ]
);
```

**Comment by LewisCraik** [comment]
That makes sense, although I do not see why both could not be used?

**Comment by mjaschen** [comment]
You're right. I'll merge your PR and update the README with a 2nd example.

**Comment by mjaschen** [comment]
Merged in #45

**Pull request closed without merging**
